### ISSUE TITLE
Should I turn off compilation optimization when testing the parallelism efficiency of MPI parallel programs?

### ISSUE THREAD

**Issue by shilei-123** [foxtran/MPI-lb#21]
I am parallelizing my fortran program using MPI, using the compiler intel visual fortran. But I've found that parallelism is always inefficient when turning on O3 level optimizations. But when I turned off compile optimization, the parallelism efficiency was as expected. So do I need to turn off the optimization option whenever I test parallelism efficiency?

**Comment by foxtran** [comment]
Hi!

I suppose that problem comes from faster computing time. You can decrease it by playing with compiler options (enabling -O3, other features like LTO), but compiler can not speed-up MPI data-transfers. As a result, you may see that time of computing was decreased, but MPI time is still huge so ratio compute time/MPI time goes down. The possible solution is to increase batch size for single MPI block to decrease number of sync points/data-transfers.

Shortly, you must test performance of your app with all possible optimization flags.

**Comment by shilei-123** [comment]
@foxtran 
HI！
Thank you for your answer. I suspect that the compiler optimization automatically parallelizes some of my code segments, which may also make my serial program not strictly serial execution, that is, when I test the serial program time, some of the program is actually running in parallel, which also affects the parallelism efficiency.
Do you think what I'm saying makes sense？

**Comment by foxtran** [comment]
With old Intel Fortran compiler (not Intel LLVM Fortran compiler), there is an extra option `-parallel` which does extra parallelization of loops. I do not know, does Intel Visual Fortran the same thing, but at -O3 level. I never used Intel Visual Fortran, so I'm not 100% sure. It is better to explicitly use OpenMP for node-level parallelism if possible to avoid such issues :)

**Comment by shilei-123** [comment]
thanks a lot！
